#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward Software Development Kit
# Copyright (C) 2009-2012 by Phorward Software Technologies, Jan Max Meyer
# http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See $PHOME/LICENSE for more information.
#
# Script:		Setenv (formerly psh)
# Author:		Jan Max Meyer
# Usage:		Phorward SDK shell configuration script
#-------------------------------------------------------------------------------

#Set PHOME
PHOME=`pwd`

if [ "`dirname $0`" != "." ]
then
	PHOME="$PHOME/`dirname $0`"
fi

#Setup development environment
SRCD=$PHOME/src
export SRCD

PATH=.:$PHOME/run:$PATH
export PATH

#Setting the CDPATH
if [ "$CDPATH" ]
then
	CDPATH=".:$PHOME/src:$CDPATH"
else
	CDPATH=".:$PHOME/src"
fi
export CDPATH

#Aliases
alias s='cd $PHOME/src'
alias i='cd $PHOME/include'
alias l='cd $PHOME/lib'
alias r='cd $PHOME/run'
alias d='cd $PHOME/doc'
alias e='cd $PHOME/etc'
alias P='cd $PHOME'
alias quit='exit'
alias q='exit'

#Set user environment
if [ -x "$PHOME/etc/userenv" ]
then
	. $PHOME/etc/userenv
fi

#Give Welcome message!
if [ "$1" != "--silent" -a "$1" != "-s" ]
then
		cat <<ENDL
:: Phorward Development Environment v`$PHOME/Version`
:: Copyright (C) 2006-2012 by Phorward Software Technologies, Jan Max Meyer
:: All rights reserved. See LICENSE for more informations.
:: `uname -n -o -p -r`
   ______________________
  /\\                     \\
 /  \\    _________________\\
 \   \\   \\                /
  \   \\   \\__________    /
   \   \\   \\    /   /   /
    \   \\   \\  /   /   /
     \   \\   \\/   /   /
      \   \\  /   /   /
       \   \\/   /   /
        \      /   /
         \    /   /
          \  /   /	PHORWARD SOFTWARE TECHNOLOGIES
           \/___/              ... all systems go!

PHOME directory is set to "$PHOME"
ENDL

fi

