#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward Software Development Kit
# Copyright (C) 2009-2011 by Phorward Software Technologies, Jan Max Meyer
# http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See $PHOME/LICENSE for more information.
#
# Script:		dmake
# Author:		Jan Max Meyer
# Usage:		Run 'make' with Debug-Flag
#-------------------------------------------------------------------------------

echo "***********************"
echo "* DEBUG MAKE :: START *"
echo "***********************"
make DEBUG=-D__WITH_TRACE=1 $*
echo "**********************"
echo "* DEBUG MAKE :: DONE *"
echo "**********************"
