#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward Software Development Kit
# Copyright (C) 2009, 2010 by Phorward Software Technologies, Jan Max Meyer
# http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See $PHOME/LICENSE for more information.
#
# Script:		dos_to_unix
# Author:		Jan Max Meyer
# Usage:		DOS to Unix ASCII-file conversion
#-------------------------------------------------------------------------------

if [ $# -lt 2 ]
then
	echo "usage: $0 infile outfile"
	exit 1
fi

tr -d '\r' <$1 >$2
