#!/bin/sh

file="$1"
desc="$2"

if [ -z "$file" ]
then
	file="noname"
fi

ARSCH=`echo $HOME | sed -e "s/\//#/g"`
module=`pwd | sed -e "s/\//#/g" | sed -e "s/$ARSCH//" | awk -F '#' '{print $2}'`

if [ "$module" ]
then
	module=" :: $module"
fi

ext=`echo $file | awk -F . '{print $NF}'`
what=""

cbeg="/* "
cend=" */"
clin=""

case "$ext" in
	"c")
		what="MODULE--"
		;;
	"h")
		what="HEADER--"
		;;
	"y"|"par")
		what="PARSER--"
		;;
	"syn"|"bnf")
		what="GRAMMAR-"
		cbeg=""
		cend=""
		clin="// "
		;;
	"sh")
		echo "#!/bin/sh"
		what="SCRIPT--"
		cbeg=""
		cend=""
		clin="# "
		;;
	"awk")
		echo "#!/bin/awk"
		what="AWK-----"
		cbeg=""
		cend=""
		clin="# "
		;;
	*)
		if [ "$file" = "Makefile" ]
		then
			what="MAKEFILE"
			cbeg=""
			cend=""
			clin="# "
		else
			what="FILE----"
		fi
		break
		;;
esac

echo "$clin$cbeg-$what--------------------------------------------------------------------"
echo "${clin}Phorward Foundation Toolkit"
echo "${clin}Copyright (C) 2006-`date +\"%Y\"` by Phorward Software Technologies, Jan Max Meyer"
echo "${clin}http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com"
echo "${clin}All rights reserved. See LICENSE for more information."
echo "${clin}"
echo "${clin}File:	$file"
echo "${clin}Usage:	$desc"
echo "${clin}-----------------------------------------------------------------------------$cend"
echo ""

