#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward C/C++ Library
# Copyright (C) 2006-2019 by Phorward Software Technologies, Jan Max Meyer
# https://phorward.info ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See LICENSE for more information.
#
# Script:		pdostounix
# Author:		Jan Max Meyer
# Usage:		DOS to Unix ASCII-file conversion
#-------------------------------------------------------------------------------

if [ $# -lt 2 ]
then
	echo "usage: $0 infile outfile"
	exit 1
fi

tr -d '\r' <$1 >$2
