#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward Software Development Kit
# Copyright (C) 2009-2012 by Phorward Software Technologies, Jan Max Meyer
# http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See $PHOME/LICENSE for more information.
#
# Script:		phelp
# Author:		Jan Max Meyer
# Usage:		Show command help
#-------------------------------------------------------------------------------

echo "d         Move to $PHOME/doc (Documentation Directory)"
echo "dmake     Run 'make' with trace define"
echo "e         Move to $PHOME/etc (Miscelleanous Directory)"
echo "ed        Edit file with $EDITOR"
echo "ex        View current directory in file explorer ($EXPLORER)"
echo "i         Move to $PHOME/include (Include Directory)"
echo "l         Move to $PHOME/lib (Library Directory)"
echo "P         Move to $PHOME (Phorward SDK root folder)"
echo "phelp     Shows this quick help"
echo "r         Move to $PHOME/run (Tools/Executable Directory)"
echo "s         Move to $PHOME/src (Source Directory)"
