#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward Software Development Kit
# Copyright (C) 2009-2012 by Phorward Software Technologies, Jan Max Meyer
# http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See $PHOME/LICENSE for more information.
#
# Script:		ppp
# Author:		Jan Max Meyer
# Usage:		Phorward Pre-Processor wrapper script
#-------------------------------------------------------------------------------

if [ $# -lt 1 ]
then
	echo "usage: $0 [ -I <include-dir> ] [ -D <define> ] <files>"
	exit 1
fi

#find cc
cc=`awk '/^CC[ \t]*=/	{	split( $0, line, "=" )
									print line[2]
								}' $PHOME/include/Make.inc`

#find stdopts
cstdopts=`awk '/^CFLAGS[ \t]*=/	{	split( $0, line, "=" )
									print line[2]
								}' $PHOME/include/Make.inc`

while [ "$1" ]
do
	case "$1" in
		-I)
			opt="$opt -I$2"

			shift
			;;
		-D)
			opt="$opt -D$2"
			shift
			;;
		*)
			break
			;;
	esac

	shift
done

while [ "$1" ]
do
	#zum glueck sind die Parameter bei MS und GNU gleich :D
	$cc -E $opt $cstdopts $1
	shift
done

