#!/bin/sh
#-------------------------------------------------------------------------------
# Phorward Software Development Kit
# Copyright (C) 2009-2012 by Phorward Software Technologies, Jan Max Meyer
# http://www.phorward-software.com ++ contact<at>phorward<dash>software<dot>com
# All rights reserved. See $PHOME/LICENSE for more information.
#
# Script:		psh
# Author:		Jan Max Meyer
# Usage:		Phorward SDK shell configuration script
#-------------------------------------------------------------------------------

#Setup development environment
SRCD=$PHOME/src
export SRCD

PATH=.:$PHOME/run:$PATH
export PATH

#Setting the CDPATH
if [ "$CDPATH" ]
then
	CDPATH=".:$PHOME/src:$CDPATH"
else
	CDPATH=".:$PHOME/src"
fi
export CDPATH

#Aliases
if [ "$PSYSTEM" = "WINDOWS" ]
then
	# WINDOWS PORT ENVIRONMENT REQUIREMENTS
	# +++++++++++++++++++++++++++++++++++++
	# Unix-Environment:		Msys
	# Compiler:				Microsoft Visual C++
	# Local File Editor:	Notepad2

	WINDOW_EXPLORER=start
	EDITOR=notepad2

	alias make='nmake //nologo $*'
	alias vi='$EDITOR $*'

	#Use Microsoft NMake on Windows
	PMAKE="nmake //nologo"
	export PMAKE
else
	WINDOW_EXPLORER=efm
	EDITOR=gedit
	USERNAME=`whoami`

	#Use GNU Make on Linux
	PMAKE=make
	export PMAKE
fi

alias s='cd $PHOME/src'
alias i='cd $PHOME/include'
alias l='cd $PHOME/lib'
alias r='cd $PHOME/run'
alias d='cd $PHOME/doc'
alias e='cd $PHOME/etc'
alias P='cd $PHOME'
alias ex='$WINDOW_EXPLORER . &'
alias ed='$EDITOR $1'
alias quit='exit'
alias q='exit'

#Set user environment
if [ -x "$PHOME/etc/userenv" ]
then
	. $PHOME/etc/userenv
fi

#Give Welcome message!
if [ "$1" != "--silent" -a "$1" != "-s" ]
then
		cat <<ENDL
:: Phorward Development Environment v`$PHOME/Version`
:: Copyright (C) 2006-2012 by Phorward Software Technologies, Jan Max Meyer
:: All rights reserved. See LICENSE for more informations.
:: `uname -n -o -p -r`
   ______________________
  /\\                     \\
 /  \\    _________________\\
 \   \\   \\                /
  \   \\   \\__________    /
   \   \\   \\    /   /   /
    \   \\   \\  /   /   /
     \   \\   \\/   /   /
      \   \\  /   /   /
       \   \\/   /   /
        \      /   /
         \    /   /
          \  /   /	PHORWARD SOFTWARE TECHNOLOGIES
           \/___/              ... all systems go!

Your shell is configured with the following parameters:
ENDL

		if [ -f "$PHOME/include/Commercial.inc" ]
		then
			echo "PSYSTEM=$PSYSTEM PHOME=$PHOME (PRIVATE SOURCES REPOSITORY)"
		else
			echo "PSYSTEM=$PSYSTEM PHOME=$PHOME"
		fi

		echo
		echo "Type 'phelp' to get a command reference of all relevant commands and tools."
fi

